#FROM node:8-alpine
ARG NODE_VERSION=8
FROM node:${NODE_VERSION}

# Home directory for Node-RED application source code.
RUN mkdir -p /usr/src/node-red

# User data directory, contains flows, config and nodes.
RUN mkdir /data
RUN mkdir /logs

COPY /data/multiwcs_cross_channels/ /data/
#COPY /data/multiwcs/ /data/

WORKDIR /usr/src/node-red

# Add node-red user so we aren't running as root.
#RUN useradd --home-dir /usr/src/node-red --no-create-home node-red \
#    && chown -R node-red:node-red /data \
#    && chown -R node-red:node-red /usr/src/node-red

#USER node-red

# package.json contains Node-RED NPM module and node dependencies
#RUN cd /data & npm install crypto-js
#RUN cd /data && npm install npm@3.7.5

#RUN cd /data && npm install address-validator
#RUN cd /data && npm install node-usps
#RUN cd/data && npm install dialogflow
COPY package.json /usr/src/node-red/
RUN npm install
RUN npm audit fix

#RUN cd /data && npm init --yes

# User configuration directory volume
EXPOSE 7990

# Environment variable holding file path for flows configuration
ENV FLOWS=multiwcs_cross_channels.json

CMD ["npm", "start", "--", "--userDir", "/data"]
